const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const session = require('express-session');

const authRouter = require('../auth/auth-router.js');
const usersRouter = require('../users/users-router.js');

const server = express();

const sessionConfig = {
    name: 'name of the cookie', // default value is session id
    secret: 'keep it secret, keep it safe - gandalf', // only our server knows this value for production store this in .env file
    cookie: {
        httpOnly: true, // true prevents access from Javascript console in the user's browser
        maxAge: 1000 * 60 * 10, // value in miliseconds so 1000 * 60 * 10 is ten minutes
        secure: false, // false allows cookies to be sent over http and true allows cookies to be sent over https
    },
    resave: false, // false prevents a cookie from automatically being generated by the server for General Data Protection Regulation (GDPR) regulations in Europe
    saveUninitialized: true, // create new session automatically, display to client that the website stores cookies
};

server.use(session(sessionConfig));
server.use(helmet());
server.use(express.json());
server.use(cors());

server.use('/api/auth', authRouter);
server.use('/api/users', usersRouter);

server.get('/', (req, res) => {
    res.send("It's alive!");
});

module.exports = server;
